// <auto-generated />
using System;
using FlexiScan.Qrs.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlexiScan.Qrs.Data.Migrations
{
    [DbContext(typeof(QrsDbContext))]
    [Migration("20260804224221_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FlexiScan.Qrs.Data.Models.CustomDomain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DomainName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DomainName")
                        .IsUnique();

                    b.ToTable("CustomDomains");
                });

            modelBuilder.Entity("FlexiScan.Qrs.Data.Models.QrCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CustomDomainId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DestinationUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrackingPixelId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomDomainId");

                    b.ToTable("QrCodes");
                });

            modelBuilder.Entity("FlexiScan.Qrs.Data.Models.UserUsageCache", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("YearMonth")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CurrentMonthScans")
                        .HasColumnType("int");

                    b.Property<bool>("IsScanLimitReached")
                        .HasColumnType("bit");

                    b.Property<int>("TotalActiveCodes")
                        .HasColumnType("int");

                    b.HasKey("UserId", "YearMonth");

                    b.ToTable("UserUsageCaches");
                });

            modelBuilder.Entity("FlexiScan.Qrs.Services.Data.ScanEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnonymizedIp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OperatingSystem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("QrCodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("QrCodeId");

                    b.ToTable("ScanEvents");
                });

            modelBuilder.Entity("FlexiScan.Qrs.Data.Models.QrCode", b =>
                {
                    b.HasOne("FlexiScan.Qrs.Data.Models.CustomDomain", "CustomDomain")
                        .WithMany()
                        .HasForeignKey("CustomDomainId");

                    b.Navigation("CustomDomain");
                });

            modelBuilder.Entity("FlexiScan.Qrs.Services.Data.ScanEvent", b =>
                {
                    b.HasOne("FlexiScan.Qrs.Data.Models.QrCode", "QrCode")
                        .WithMany()
                        .HasForeignKey("QrCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QrCode");
                });
#pragma warning restore 612, 618
        }
    }
}
