<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>e6c593d7-208d-45ee-8d94-30ef6d352e3f</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="5.6.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.10" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BeatCheck.Users.Data.Models\BeatCheck.Users.Data.Models.csproj" />
    <ProjectReference Include="..\BeatCheck.Users.Data\BeatCheck.Users.Data.csproj" />
    <ProjectReference Include="..\BeatCheck.Users.Services.Data\BeatCheck.Users.Services.Data.csproj" />
    <ProjectReference Include="..\BeatCheck.Users.Web.Infrastructure\BeatCheck.Users.Web.Infrastructure.csproj" />
  </ItemGroup>

</Project>
