// <auto-generated />
using System;
using FlexiScan.Subscriptions.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlexiScan.Subscriptions.Data.Migrations
{
    [DbContext(typeof(SubscriptionsDbContext))]
    [Migration("20260801214024_RenamedMonthlyToDailyColumnScans")]
    partial class RenamedMonthlyToDailyColumnScans
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FlexiScan.Subscriptions.Data.Models.BillingCustomer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("StripeCustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BillingCustomers");
                });

            modelBuilder.Entity("FlexiScan.Subscriptions.Data.Models.SubscriptionPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StripeProductId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SubscriptionPlans");
                });

            modelBuilder.Entity("FlexiScan.Subscriptions.Data.Models.SubscriptionPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Interval")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("StripePriceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubscriptionPlanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionPlanId");

                    b.ToTable("SubscriptionPrices");
                });

            modelBuilder.Entity("FlexiScan.Subscriptions.Data.Models.UserSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BillingCustomerId")
                        .HasColumnType("int");

                    b.Property<bool>("CancelAtPeriodEnd")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CurrentPeriodEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CurrentPeriodStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StripeSubscriptionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubscriptionPriceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BillingCustomerId");

                    b.HasIndex("SubscriptionPriceId");

                    b.ToTable("UserSubscriptions");
                });

            modelBuilder.Entity("FlexiScan.Subscriptions.Data.Models.SubscriptionPlan", b =>
                {
                    b.OwnsOne("FlexiScan.Subscriptions.Data.Models.PlanFeatures", "Features", b1 =>
                        {
                            b1.Property<int>("SubscriptionPlanId")
                                .HasColumnType("int");

                            b1.Property<bool>("AllowApiAccess")
                                .HasColumnType("bit");

                            b1.Property<bool>("AllowCustomDomains")
                                .HasColumnType("bit");

                            b1.Property<bool>("AllowCustomLogos")
                                .HasColumnType("bit");

                            b1.Property<bool>("AllowTrackingPixels")
                                .HasColumnType("bit");

                            b1.Property<bool>("HasAdvancedAnalytics")
                                .HasColumnType("bit");

                            b1.Property<int>("MaxActiveCodes")
                                .HasColumnType("int");

                            b1.Property<int>("MaxDailyScans")
                                .HasColumnType("int");

                            b1.HasKey("SubscriptionPlanId");

                            b1.ToTable("SubscriptionPlans");

                            b1.WithOwner()
                                .HasForeignKey("SubscriptionPlanId");
                        });

                    b.Navigation("Features")
                        .IsRequired();
                });

            modelBuilder.Entity("FlexiScan.Subscriptions.Data.Models.SubscriptionPrice", b =>
                {
                    b.HasOne("FlexiScan.Subscriptions.Data.Models.SubscriptionPlan", "SubscriptionPlan")
                        .WithMany("SubscriptionPrices")
                        .HasForeignKey("SubscriptionPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubscriptionPlan");
                });

            modelBuilder.Entity("FlexiScan.Subscriptions.Data.Models.UserSubscription", b =>
                {
                    b.HasOne("FlexiScan.Subscriptions.Data.Models.BillingCustomer", "Customer")
                        .WithMany("Subscriptions")
                        .HasForeignKey("BillingCustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlexiScan.Subscriptions.Data.Models.SubscriptionPrice", "SubscriptionPrice")
                        .WithMany("UserSubscriptions")
                        .HasForeignKey("SubscriptionPriceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("SubscriptionPrice");
                });

            modelBuilder.Entity("FlexiScan.Subscriptions.Data.Models.BillingCustomer", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("FlexiScan.Subscriptions.Data.Models.SubscriptionPlan", b =>
                {
                    b.Navigation("SubscriptionPrices");
                });

            modelBuilder.Entity("FlexiScan.Subscriptions.Data.Models.SubscriptionPrice", b =>
                {
                    b.Navigation("UserSubscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
